# Common array operations
Now that we've gone through different ways of creating an array, let's go into some of the common array operations like 

In [ ]:
import numpy as np # type: ignore

In [2]:
# an array with weight in pounds
array = np.array([140, 174, 166, 192])
array

array([140, 174, 166, 192])

In [3]:
# divide by 2.2 to get values in kilos
array / 2.2

array([63.63636364, 79.09090909, 75.45454545, 87.27272727])

## Reshaping arrays

In [4]:
array = np.ones((3,4))
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
array.reshape((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# reshaping has to keep the same number of items
array.reshape((12,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [7]:
# otherwise you get into trouble
array.reshape((5,1))

ValueError: cannot reshape array of size 12 into shape (5,1)

In [ ]:
# flatten arrays
print(array)
array.flatten()