# More array operations


In [5]:
import numpy as np

## Expanding arrays

In [6]:
# create a single dimension array
array = np.ones((4,))
print(array)
print(array.shape)

# expand one row
expanded = array[np.newaxis, :]
expanded.shape

[1. 1. 1. 1.]
(4,)


(1, 4)

## Conditional new arrays

In [7]:
array = np.array([[3,12,11],[45,22,11],[56,15,22]])
# represent all matching conditions
print(array < 20)

[[ True  True  True]
 [False False  True]
 [False  True False]]


In [8]:
# produce all matching values
array[array < 20]

array([ 3, 12, 11, 11, 15])

## Slicing

Similar to Python lists, but with more features and capabilities

In [9]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [10]:
# give a range
a[1:4]

array([1, 2, 3])

## Stacking


In [11]:
# horizontally
# must have same number of dimensions!
first = np.full((2, 12), 2)
print(first)
second = np.full((2, 7), 2)
print(second)
np.hstack((first, second))

[[2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2]]
[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]


array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [12]:
# stacking vertically
first = np.full((3,3), 1)
print(first)
second = np.full((3,3), 2)
print(second)
np.vstack((first, second))


[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])


## Splitting arrays

In [13]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# split into two equal parts
# warning it needs to allow for an equal division!
np.hsplit(array, 2)


[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [15]:
# this allows for "unpacking"
first, second = np.hsplit(array, 2)
print(first)
print(second)

[1 2 3 4 5]
[ 6  7  8  9 10]
